### ISSUE TITLE
Restoring Single Binary

### ISSUE THREAD

**Issue by jalcine** [JakeBecker/elixir-ls#14]
So with the removal of https://github.com/JakeBecker/elixir-ls/commit/f3ca5bf2d423c87dcfbd8e4bc7007698ad8d0390, it's been difficult for me to use this plugin within Neovim via https://github.com/roxma/nvim-completion-manager. For now, I had to pin the repo to that commit in my setup. Do you have a suggestion on how to still use the LanguageClient -> Server flow without having to use `mix` to start the server?

**Comment by jalcine** [comment]
No, sorry. Commit in question is this one: https://github.com/JakeBecker/elixir-ls/commit/6bd1264d5206dd72a9e2c2dbe65552644ae905dd

**Comment by JakeBecker** [comment]
It's cool that you're using it with NeoVim! I didn't know there were language server plugins available for it.

Would a shell script work for launching it? I had to add shell scripts to launch the debugger in the VS Code plugin: https://github.com/JakeBecker/vscode-elixir-ls/tree/master/scripts

**Comment by jalcine** [comment]
I have to try it out. Off the top of my head; it'd need to use the stdio/stdout approach with this. I'll dig into this

**Comment by JakeBecker** [comment]
It does use the stdio approach, and it seems to work fine when launching the debugger from a .sh or .bat file in VS Code.

If you get it working, would you be interesting in publishing the client as a NeoVim package? If you do, I'll start a list of clients in the Readme and include it there.

**Comment by hauleth** [comment]
I have tried to build package for (Neo)Vim, but got error:

```
** (ErlangError) Erlang error: {:invalid_status, {:noappfile, "/Users/hauleth/Workspace/JakeBecker/elixir-ls/_build/shared/lib/language_server/ebin/language_server.app"}}
    lib/mix/tasks/archive/build.deps.ex:77: anonymous fn/3 in Mix.Tasks.Archive.Build.Deps.list/1
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/archive/build.deps.ex:54: Mix.Tasks.Archive.Build.Deps.build_archives/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

**Comment by JakeBecker** [comment]
Hm. My guess is that the language server project isn't compiled. Make sure you do `mix compile` from the umbrella root first, then try `mix release -o <release_dir>`. If that doesn't work, try doing `mix deps.clean --all && mix clean && mix deps.get && mix compile` and then try again.

**Comment by hauleth** [comment]
Still cannot compile. Error:

```
== Compilation error in file lib/language_server/dialyzer.ex ==
** (CompileError) lib/language_server/dialyzer.ex:396: Mix.Task.Compiler.Diagnostic.__struct__/1 is undefined, cannot expand struct Mix.Task.Compiler.Diagnostic
```

**Comment by JakeBecker** [comment]
You need to build with Elixir 1.6, which is still pre-release. I recommend installing kiex, then running `kiex install master`: https://github.com/taylor/kiex

**Comment by hauleth** [comment]
@JakeBecker so you need update in README as there requirements are Elixir 1.3+. I am using asdf, but I trusted your README.

**Comment by JakeBecker** [comment]
Ah. I meant in the README that running it requires Elixir 1.3. I'll add the version requirement to the umbrella project's mixfile.

**Comment by hauleth** [comment]
You know, without binary distribution it is pointless to include runtime requirements in readme ;)

**Comment by JakeBecker** [comment]
I added the version requirement in the mixfile: https://github.com/JakeBecker/elixir-ls/commit/2e407f6e12998ea78603f997604ca0ce4dbb6897

**Comment by hauleth** [comment]
I have created issue #25 which should help NeoVim users like me and overall simplify distribution and project adoption.

**Comment by jalcine** [comment]
I ended up writing a shell script that I had [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) use in order to communicate with the server.

**Comment by jalcine** [comment]
With that, I'll close this issue (and link my script in my setup shortly).

**Comment by jalcine** [comment]
https://github.com/jalcine/vimrc/blob/aa9f0aa910af1920696cc2bb08ce4eff6c617e23/home/.local/bin/neovim-language-server-elixir

**Comment by hauleth** [comment]
@jalcine your script seems a little bit complicated. I am using vim-lsp instead of LanguageClient-neovim and all I needed was to use proper launch command:

```viml
[&shell, &shellcmdflag, 'env ERL_LIBS=/Users/hauleth/Workspace/JakeBecker/elixir-ls/lsp mix elixir_ls.language_server']
```

**Comment by jalcine** [comment]
What version of this repository are you using? I'm on `master` and didnt' find `elixir_ls.language_server` as a target.

I also cut out the function defined in that script - I haven't pushed it up yet.

**Comment by hauleth** [comment]
I am using c8a6912 commit and I have just built everything into `.ez` and then used it as I have showed.

**Comment by jalcine** [comment]
Interesting. I'll revisit this when I have some time. What I think should happen, long-term, is someone wrapping this in a Vim plugin and potentially exposing an API that'd return the path to said binary (kinda similar to how the VS code plugin for TypeScript directly install its Node dependency - to isolate it a bit).
