### ISSUE TITLE
vim support

### ISSUE THREAD

**Issue by henry-hz** [JakeBecker/elixir-ls#35]
any chance to add vim (or neovim) support ?
thanks!

**Comment by hauleth** [comment]
Achieving Vim support isn't that hard, however due to #25 it isn't quite automated. I am using [`vim-lsp`](https://github.com/prabirshrestha/vim-lsp/blob/master/README.md) with ElixirLS and configuration is quite easy.

Steps to reproduce:

- fetch ElixirLS
- build using Elixir 1.6 (required) via `mix release -o lsp`
- To your `$MYVIMRC` add:
```
augroup elixir_lsp
  au!
  au User lsp_setup call lsp#register_server({
    \ 'name': 'elixir-ls',
    \ 'cmd': {server_info->[&shell, &shellcmdflag, 'env ERL_LIBS=<path to your elixir-ls clone>/lsp mix elixir_ls.language_server']},
    \ 'whitelist': ['elixir', 'eelixir'],
    \ })
augroup END
```

[Prebuilt package, built on macOS Sierra, but should work anywhere](https://github.com/JakeBecker/elixir-ls/files/1557064/lsp.tar.gz)

**Comment by kamilchm** [comment]
I use [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) with a little different approach. I treat every project as a language server provider itself. I work with different environments where I sometimes need specific versions of Python, OCaml or Node, so I use pip, opam or npm to get proper language server for each project and my vim starts the server with simple `pyls`, `ocaml-language-server` ...
I did something similar with `elixir-ls` starting it as mix task, calling `ElixirLS.LanguageServer.CLI.main()` in it. It's now easier to manage `elixir-ls` as `:dev` only dependency in my project.

@JakeBecker what do you think about adding simple mix task as part of `elixir-ls`?

**Comment by jparise** [comment]
I added support for ALE here: w0rp/ale#1956

**Comment by joaquinalcerro** [comment]
Just as a reference for other people that encounters this issue I finally solve the problem.

The compilation error was because the dialyzer source code was not installed by default. So I installed it.

**Comment by GrzegorzKozub** [comment]
I created a Vim plugin that automates elixir-ls download and compilation so we can use it with ALE in a more self-contained manner: [vim-elixirls](https://github.com/GrzegorzKozub/vim-elixirls).

**Comment by andyl** [comment]
@GrzegorzKozub - I've been using vim-elixirls - bravo - many thanks for posting this plugin.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins if you're using VS Code.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
